name: build-and-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call: # make sure this workflow can be called

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0
    
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
    
      - name: Restore dependencies
        run: dotnet restore
    
      - name: Build project
        run: dotnet build --configuration Release --no-restore
    
      - name: Test project
        run: dotnet test --configuration Release --no-build --no-restore