name: build-and-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call: 
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
    
      - name: Restore dependencies
        run: dotnet restore
    
      - name: Build project
        run: dotnet build --configuration Release --no-restore
    
      - name: Test project
        run: dotnet test --configuration Release --no-build --no-restore
    
      - name: Publish build artifacts
        run: dotnet publish --configuration Release --output ./artifacts
    
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./artifacts