name: release

on:
  push:
    tags:
      - 'v*'  # This triggers the action on new version tags

jobs:
  build:
    uses: ./.github/workflows/build.yml  # Call the reusable build workflow

  release:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes first

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./artifacts
          
      - name: Set version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Pack .NET tool
        run: dotnet pack ./artifacts --configuration Release -p:Version=${{ env.VERSION }} --output ./out --no-build --no-restore
        
      - name: Publish to NuGet
        run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}