name: Publish .NET Console App

on:
  push:
    tags:
      - 'v*'  # This triggers the action on new version tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/build.yml
      - name: Set version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Pack .NET tool
        run: dotnet pack -c Release -o out -p:Version=${{ env.VERSION }}
        
      - name: Publish to NuGet
        run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}